# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm i -D @playwright/test
    npx playwright install
  displayName: 'npm install and build'

- script: |
    npx playwright test --workers 8
  continueOnError: true
  displayName: 'execute tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit' 
    testResultsFiles: 'report.xml' 
    #searchFolder: '$(System.DefaultWorkingDirectory)' # Optional
    #mergeTestResults: false # Optional
    failTaskOnFailedTests: true
    testRunTitle: 'Playwright on Azure Devops'
    #buildPlatform: # Optional
    #buildConfiguration: # Optional
    publishRunAttachments: true